version: "3.9"

networks:
  algafood-network:
    driver: bridge

services:
  algafood-api-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    networks:
      - algafood-network

  algafood-api:
    image: algafood-api
    environment:
      DB_HOST: algafood-api-mysql
    ports:
      - "8080:8080"
    networks:
      - algafood-network
    depends_on:
      - algafood-api-mysql