version: "3.9"

networks:
  algafood-network:
    driver: bridge

services:
  algafood-api-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    networks:
      - algafood-network

  algafood-api:
    image: algafood-api
#    command: [ "/wait-for-it.sh", "-t", "30", "algafood-api-mysql:3306", "--","java", "-jar", "algafood-api.jar" ]
    command: [ "/wait-for-it.sh", "-t", "30", "algafood-api-mysql:3306", "--","java", "-Djava.io.tmpdir=/tmp/algafood", "-Dserver.tomcat.basedir=/tmp/algafood/tomcat", "-jar", "algafood-api.jar" ]
    environment:
      DB_HOST: algafood-api-mysql
    ports:
      - "8081:8080"
    volumes:
      - ./tmp:/tmp/algafood  # Mapeia volume para persistência
    networks:
      - algafood-network
    depends_on:
      - algafood-api-mysql